# Generated by Django 3.2.5 on 2021-07-20 04:11

from django.db import migrations, models
import django.db.models.deletion
import travelBook.models


class Migration(migrations.Migration):

    dependencies = [
        ('travelBook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=travelBook.models.handle_upload)),
                ('ImageFolder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='travelBook.imagefolder')),
            ],
        ),
    ]
