# Generated by Django 3.2.5 on 2021-07-21 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import travelBook.models


class Migration(migrations.Migration):

    dependencies = [
        ('travelBook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=999, null=True)),
                ('city', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=30)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=travelBook.models.handle_upload)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='travelBook.imagefolder')),
            ],
        ),
    ]
