# Generated by Django 3.2.5 on 2021-07-20 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelBook', '0002_image_imagefolder'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefolder',
            name='country',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='imagefolder',
            name='city',
            field=models.CharField(max_length=20),
        ),
    ]
