# Generated by Django 3.2.5 on 2021-07-21 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelBook', '0002_image_imagefolder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagefolder',
            old_name='created_date',
            new_name='created_at',
        ),
    ]
