# Generated by Django 3.2.5 on 2021-07-20 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelBook', '0003_auto_20210720_0029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='ImageFolder',
            new_name='folder',
        ),
    ]
