# Generated by Django 3.2.5 on 2021-07-20 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelBook', '0004_rename_imagefolder_image_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefolder',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='folder', to=settings.AUTH_USER_MODEL),
        ),
    ]
